version: '3.8'

services:
  forge4flame:
    image: provabottone
    ports:
      - "3839:3838"
    volumes:
      - shared-data:/home/docker/flamegpu2/FLAMEGPU-FORGE4FLAME/resources
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/shared-socket:/tmp/shared-socket  
    container_name: forge4flame-container
    restart: unless-stopped

  flamegpu:
    image: francesco2310/forge4flame:flamegpu
    container_name: flamegpu2-container
    runtime: nvidia
    stdin_open: true
    tty: true
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - shared-data:/home/docker/flamegpu2/FLAMEGPU-FORGE4FLAME/resources
      - /tmp/shared-socket:/tmp/shared-socket 

volumes:
  shared-data:
    driver: local
